eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/web-eureka/eureka/
    # 但你不想整合Eureka，也可以通过下面的配置关闭
    enabled: true
server:
  port: 9098
  servlet:
    # 由于gateway用的是webflux，所以这个设定其实是不生效的，现在还没有一个key来设定webflux的context-path
    context-path: /web-server-gateway
spring:
  application:
    name: application-server-gateway
  cloud:
    gateway:
      # default-filters: 里面可以定义一些共同的filter，对所有路由都起作用
      default-filters:
        # - TokenCheck
      routes:
        # --------------------------------转发到微服务------------------------------------
        - id: 2-application-client-demo
           # uri: lb://xxx , lb 代表从注册中心获取服务,ws请求为lb:ws://xxx
          uri: lb://application-client-demo
          predicates:
            - Path=/web-client-demo/**
        # --------------------------------转发到外部域名------------------------------------
        - id: 2-voidm-blog
          uri: http://voidm.com
          predicates:
            - Path=/2blog/**
          # StripPrefix=1表示 比如请求/2blog/**，去除掉前面一个前缀之后，最后转发到目标服务的路径为/**
          # 也可以通过 RewritePath 来实现
          filters:
            - StripPrefix=1
            #- RewritePath=/2blog/(?<segment>.*), /$\{segment}
      # gateway开关
      enabled: true