server:
  port: 9091
  servlet:
    context-path: /web-config-client
spring:
  application:
    name: application-config-server
  cloud:
    config:
      uri: http://localhost:9090/web-config-server
      profile: pro
      label: master