eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/web-eureka/eureka/
server:
  port: 8084
  servlet:
    context-path: /web-service-demo-feign
spring:
  application:
    name: application-service-demo-feign