eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/web-eureka/eureka/
  # eureka Client列表显示地址信息
  # 如果项目配置有 server.servlet.context-path 属性，想要被 spring boot admin 监控，就要配置以下属性
  instance:
    metadata-map:
      management:
        context-path: /web-client-demo/actuator
    health-check-url: http://${eureka.instance.ip-address}:${server.port}/web-client-demo/actuator/health
    status-page-url: http://${eureka.instance.ip-address}:${server.port}/web-client-demo/actuator/info
    home-page-url: http://${eureka.instance.ip-address}:${server.port}/web-client-demo
    # 显示的实力名称
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
    # instance-id: ${spring.application.name}:${server.port}
    # 使用IP替代实例名
    prefer-ip-address: true
    # 实力的IP地址
    ip-address: 127.0.0.1
    # 服务注册中心实例的主机名
    hostname: 127.0.0.1
server:
  port: 8081
  servlet:
    # Web项目路径
    context-path: /web-client-demo
spring:
  application:
    name: application-client-demo
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
      probability: 1.0

# 配置actuator开放节点
management:
  endpoints:
    web:
      exposure:
        include: "*"