eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/web-eureka/eureka/
server:
  port: 8081
  servlet:
    context-path: /web-client-demo
spring:
  application:
    name: application-client-demo