server:
  port: 9090
  servlet:
    # Web根路径
    context-path: /web-config
spring:
  application:
    # 应用名称
    name: application-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marlkiller/SpringCloud-Project
          search-paths: /config-server
      label=master: master